import type { Metadata } from "next";
import "./globals.css";
import Providers from "./store/Providers";
import Loader from "./components/custom/Loader";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body>
				<Providers>
					<Loader />

					{children}
				</Providers>
			</body>
		</html>
	);
}
